### PR TITLE
chore: start adding docstrings

### PR DESCRIPTION
**Pull request by Rex2002**
PR for tracking audio technical documentation

### CODE REVIEW

**Comment by Rex2002** [comment]
- [ ] add docstrings to harmonizer
- [ ] add docstrings to Backing

I think these should be the last documentations for the audio-part

**Comment by nichtLehdev** [comment]
I'll do the Harmonizer part after testing tomorrow

**Review by MalteRichert — APPROVED** [review]
I'm going to leave the detailed docstring review to @nichtLehdev but I like what I'm seeing.

**Comment by MalteRichert** [comment]
Going to merge this now to keep main up to date.

**Pull request merged**
