### PR TITLE
data: Gaussian blur, trendbreaks, adapted flag

### PR DESCRIPTION
**Pull request by MalteRichert**

### CODE REVIEW

**Comment by ArtInLines** [comment]
@JakobPK didn't you see this was done (just not tested yet)? Because I can't see most of the code, that should be there (like the `gaussianBlur` function for example). Did you maybe forget to push some commits?

**Comment by ArtInLines** [comment]
@JakobPK 👍 thx I'll look over the code now then :)

**Comment by MalteRichert** [comment]
I only scanned the code quickly but it seems weird that isRising is never used. Maybe check whether the variable can be removed completely or whether it might be combined with isFalling since they will probably be mutually exclusive.

**Comment by ArtInLines** [comment]
Lookd through the gaussianBlur method right now and it looks good, except that it's not a gaussian Blur. You are just taking the average, which is also valid and should also work, but it's just named wrongly then. For a gaussian blur, you would need to weigh the values closer to the current value higher in your average (specifically, the weighing would be defined via the gaussian normal distribution).

**Pull request closed without merging**
