### PR TITLE
Fix #84

### LINKED ISSUE #84: Let user remove sonifiables again
Currently there is no way for the user to remove a sonifiable from the middle pane again, after they added it. Providing a little `x` that removes it would improve UX quite a bit, I feel like. The corresponding method in the mapping - `rmSonifiable` - would need to be expanded then, however. Specifically, if the user had mapped the sonifiable to some sound parameters, we would like to remove it from the mapping completely, which the function doesn't do yet.

### PR DESCRIPTION
**Pull request by ArtInLines**
There is a closing `x` icon for every sonifiable now. Clicking that removes it from the screen. It also unchecks the stock in the search-area (if it's still there). And lastly, it updates the mapping, which in turn might update the list of used instruments which is shown. I think that should be everything that should react to the user removing a sonifiable

### CODE REVIEW

**Comment by ArtInLines** [comment]
I feel like most of these commits shouldn't be shown here. I'm not sure if I'm just too dumb to use git or if it's because the branch was based off of `enable-system-testing` instead of `main` originally.

**Comment by MalteRichert** [comment]
That shouldn’t matter matter when you just squash and merge. And conflicts shouldn’t exist anyways

**Comment by ArtInLines** [comment]
Ah ok good to know 👍

**Review by MalteRichert — APPROVED** [review]
The code looks good and it works smoothly. Nicely done!

**Pull request merged**
