### PR TITLE
Dynamic interval length

### PR DESCRIPTION
**Pull request by ArtInLines**
- StateManager dynamically sets desired interval length based on the date-range chosen by the user
- DataRepo makes different API requests depending on the Interval-length
- DataRepo gets all data in date-range, even if it requires several api requests

### CODE REVIEW

**Review by Rex2002 — APPROVED** [review]
looks nice, 
I noticed a bug earlier, where the app would crash when the api returned no data, but that should be solved with line 420 in dataRepo, right?

**Comment by ArtInLines** [comment]
@Rex2002 yes it should be. Though it might be that later code still assumes that the price-lists aren't empty and so it could still be that the app crashes tbh. But the StateManager should catch that in the future and give an error message in that case

**Comment by ArtInLines** [comment]
Just noticed a bug, oops. I am adding the prices in the wrong order, which leads to an x axis like this
grafik

I will fix this in a moment

**Comment by ArtInLines** [comment]
aaaaaaand fixed

**Pull request merged**
