### PR TITLE
Fix #129

### LINKED ISSUE #129: Sinnvolles Interface bei Daten-Analyse
Der State-Manager muss an sich einfach nur 7 Funktionen gegeben bekommen, die er aufrufen kann. Teilweise müssten diese Funktionen jedoch die selben Berechnungen durchführen (z.B. `FlagFormation` muss die Flaggen-Formationen berechnen, `Trendbreak` brauch jedoch auch die berechneten Flaggen-Formationen). Entsprechend würde es sich lohnen, diese in einer Klasse zu packen und solche Ergebnisse über Attribute im Objekt zu cachen.

### PR DESCRIPTION
**Pull request by ArtInLines**
I made a nicer interface for using the dataAnalyzer. This builds on #150, so we now can pick all options (no more "xxx not yet implemented"). I also cache calculations that might be needed repeatedly. I also fixed some bugs in the dataAnalyzer that mainly caused outOfBoundsException (for example not iterating until i == length)

@JakobPK please make sure you are happy with the changes I made in the dataAnalyzer

Edit: I also just merged the most recent changes that @JakobPK made on the dataFix branch

@MalteRichert - I know there is much to simplify and cut because it's not used anymore. I didn't want to change too much in the dataAnalyzer without having @JakobPK look over it first, but I wouldn't be surprised if you found some part in the StateManager that could be simplified too xD

### CODE REVIEW

**Review by JakobPK — COMMENTED** [review]
Skipped over the music part, but the dataAnalysis looks great to me. Thx for the Blur btw

**Comment by ArtInLines** [comment]
@JakobPK I merged your changes from the DataFix branch. It would probably be best if you continued working on this branch instead, because the DataFix branch is very behind main. Also, nice, that you cleaned up the resources folder. I updated the new paths in the code where we were using the resources too now, so the app actually works again now. Btw, if you use this branch, you can also test your work. First you can see if your changes cause any bugs/crashes of course, but secondly you can also try out mapping the formations / events to sound and see if something reasonable comes out. You can only do that on this branch (or one that is based on this one though), because your analysis was not fully integrated into the app before

@nichtLehdev As you probably saw, @JakobPK added some testfiles for you. Test them on this branch (as it is more up to date, doesn't crash and  actually integrates the changes into the StateManager).

**Comment by ArtInLines** [comment]
Also I think it would be useful to merge this into main rather sooner than later, as it has many fixes and improvements

**Review by Rex2002 — APPROVED** [review]
:100:

**Pull request merged**
