### PR TITLE
fix(mixer): reduce volume of backing track

### LINKED ISSUE #100: Backing sounds shouldn't be confuse-able with sound effects
Specifically, `108_4_fill_0_autumn.wav` has a little chime at around the 7 second mark. Effects like that chime could seem to the user like it came from some mapped sound-parameter (like some trend-line break or something like that)

### PR DESCRIPTION
**Pull request by MalteRichert**
resolve #100 code-sided

### CODE REVIEW

**Review by ArtInLines — APPROVED** [review]
Looks good to me 👍

**Review by Rex2002 — COMMENTED** [review]
did you test that with EvInstrs? 
because I am not quite sure, if the backing remains the last stream of the matrix, if EventInstruments are added (concat method somewhere in Util I think)

**Comment by MalteRichert** [comment]
@Rex2002 good point! Check out the latest commit, now backing should always be the last audioStream (which funnily enough kinda is analog mixer best practice)

**Review by Rex2002 — APPROVED** [review]
:+1:

**Pull request merged**
