### PR TITLE
feat: should resolve #81 by adding padding on both sides

### LINKED ISSUE #81: Pad all price-lists to have the same length
In #47 we decided that we set the price-values to zero for a given time, if the sonifiable has no data for said time and another one does. This still has to be done

### PR DESCRIPTION
**Pull request by Rex2002**

### CODE REVIEW

**Review by MalteRichert — APPROVED** [review]

**Comment by MalteRichert** [comment]
Looks good, but this only works for whole days, right? Can it happen that the difference is a fraction of day once we get data by minute or hour?

**Review by ArtInLines — APPROVED** [review]
Looks good to me too, but @MalteRichert raised a good concern. PR #99 adds those differnt interval lengths.
Another concern that just came to me, though I'm not sure if we might not want to just ignore that:
Let's say that we don't have data for Stock A on Day x and we don't have data for Stock B on Day y. They might now have he exact same length and we would thus not pad either of them. However, what we would probably actually want is to add data for Stock A on day x and add data for Stock B on day y.

**Comment by Rex2002** [comment]
@MalteRichert 
Im not sure if this is a problem, because the "interval"-parameter is not used (I just forgot to remove it, after changing to an approach which does not use it) and since we do all calculation based upon the length, the padding should work regardless of the data intervals I believe
@ArtInLines 
that's a good point, the only idea I managed to come up to solve this (creating some sort of day-hasData-matrix and then recreating the price list based on that matrix) seems to be annoyingly complicated, do we now how often this happens / if it could be ignored? :sweat_smile:

**Comment by ArtInLines** [comment]
@Rex2002 hmmm, I have no idea tbh. It does sound pretty annoying ngl. I have seen it happen that the api doesn't have data for some time periods in lower intervals (eg. 5min or 1hour). For testing, I set those values to 0s:
grafik
The shown stocks are exxon mobile and vodafone. So it does seem to happen sometime.
We could of course just set those values to 0 in the DataRepo already (like I did to get this picture), but then we should maybe go through the padded price lists again and remove any values where we only have 0s for all stocks

**Comment by Rex2002** [comment]
would we be able to interpolate those data-gaps (without to much effort) and just hope they are never too big?

**Comment by ArtInLines** [comment]
Yes that would be possible. Wouldn't that be basically what we discussed in the third question of #47. Imo there are two different questions here:

- What do we do with missing prices for audio (I.e. interpolation or setting to 0)
- What do we do with missing prices for Visualization (I.e.setting to 0 (looks shit) or leaving out of graph/interpolating)

In my opinion these two questions can be answered independently from each other

**Comment by Rex2002** [comment]
can we merge this one then to main?

**Comment by ArtInLines** [comment]
Yes, I'd say so 👍

**Pull request merged**
