### PR TITLE
Better export name

### PR DESCRIPTION
**Pull request by MalteRichert**

### CODE REVIEW

**Review by ArtInLines — APPROVED** [review]
Should we just go ahead and add the names of all sonifiables then? Should be relatively easily solved with a simple loop that concatenates all names in a StringBuilder, right?

Not very important though, and i'm not sure if the names wouldn't be too long then 🤷

**Comment by MalteRichert** [comment]
@ArtInLines I thought the same. All names could be too long, all symbols would be a nice solution but I can't really be bothered to do that now. It's just a neat gimmick as it is.

**Comment by ArtInLines** [comment]
I like it anyways 👍

**Comment by MalteRichert** [comment]
@ArtInLines I took this as a challenge xd

**Review by ArtInLines — APPROVED** [review]
💯

**Pull request merged**
